CREATE DATABASE RECEIPT;

CREATE TABLE CLIENT
(
    CLIENT_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255)
);

ALTER TABLE CLIENT ADD COLUMN USERNAME VARCHAR(255);
ALTER TABLE CLIENT ADD COLUMN PASSWORD VARCHAR(255);

INSERT INTO CLIENT(CLIENT_ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) 
VALUES(1, 'Test', 'John', 'Smith', 'johnsmith@gmail.com', 'password');